### PR TITLE
Update MAINTAINERS.MD

### PR DESCRIPTION
**Pull request by hdamker**
#### What type of PR is this?

Add one of the following kinds:

* subproject management

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for reviewers:

Liste Maintainers already added to @camaraproject/device-quality-indicator_maintainers

### CODE REVIEW

**Comment by hdamker** [comment]
cc:  @camaraproject/device-status_maintainers

**Comment by eharrison24** [comment]
Hi Herbert,

Are you asking that we review the maintainers for for device quality by adding the company and then the maintainers name?

**Comment by eharrison24** [comment]
Ah, disregard my last message. I see! It seems like you added the names. I don't believe this format is present in the other repos. I think this would be a very useful way to go about it in the other repos. If that is what you are suggesting.

Best,
Evan

**Comment by hdamker** [comment]
@eharrison24 the initial list is based on the table I got from APIBacklog. Waiting for approval from the nominated maintainers (the Team is already setup).

**Review by bigludo7 — APPROVED** [review]

**Comment by hdamker** [comment]
@eharrison24 would you approve as one of the Codeowners for this file (I can't approve my own PR)

**Review by eric-murray — APPROVED** [review]

**Review by eharrison24 — APPROVED** [review]

**Pull request merged**
